# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        sudo apt-get install libsqlcipher-dev
        python -m pip install sqlcipher3-binary requests
    
    - name: Run Sample
      run: |
        python sample.py

    - name: Commit sample db
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update sqlite db file"
        git push
